import { Shop } from '@/types/shop/shop'

export const fakeShops: (Shop & { memberPackage?: string })[] = [
  {
    id: '1',
    shopname: 'Shop Hoa Tươi',
    description: 'Chuyên cung cấp hoa tươi nhập khẩu',
    logoURL: '/assets/10.png',
    coverImageURL: '/assets/11.png',
    ratingAverage: 4.7,
    totalAverage: 120,
    registrationDate: new Date('2023-01-10'),
    approvalStatus: 'approved',
    approvalDate: new Date('2023-01-12'),
    bankAccountNumber: '123456789',
    bankName: 'Vietcombank',
    taxNumber: '1234567890',
    totalProduct: 80,
    completeRate: 98,
    status: true,
    accountId: 'acc1',
    createdBy: 'admin',
    createdAt: '2023-01-10',
    lastModifiedAt: '2023-01-12',
    lastModifiedBy: 'admin',
    memberPackage: 'Vàng',
  },
  {
    id: '2',
    shopname: 'Shop Đồ Gia Dụng',
    description: 'Đồ gia dụng chất lượng cao',
    logoURL: '/assets/12.png',
    coverImageURL: '/assets/13.png',
    ratingAverage: 3.9,
    totalAverage: 80,
    registrationDate: new Date('2023-02-15'),
    approvalStatus: 'pending',
    approvalDate: new Date('2023-02-16'),
    bankAccountNumber: '987654321',
    bankName: 'Techcombank',
    taxNumber: '9876543210',
    totalProduct: 120,
    completeRate: 90,
    status: true,
    accountId: 'acc2',
    createdBy: 'admin',
    createdAt: '2023-02-15',
    lastModifiedAt: '2023-02-16',
    lastModifiedBy: 'admin',
    memberPackage: 'Bạc',
  },
  {
    id: '3',
    shopname: 'Shop Thời Trang',
    description: 'Thời trang nam nữ cao cấp',
    logoURL: '/assets/13.png',
    coverImageURL: '/assets/14.png',
    ratingAverage: 4.2,
    totalAverage: 100,
    registrationDate: new Date('2023-03-20'),
    approvalStatus: 'rejected',
    approvalDate: new Date('2023-03-22'),
    bankAccountNumber: '111222333',
    bankName: 'BIDV',
    taxNumber: '1112223334',
    totalProduct: 60,
    completeRate: 85,
    status: false,
    accountId: 'acc3',
    createdBy: 'admin',
    createdAt: '2023-03-20',
    lastModifiedAt: '2023-03-22',
    lastModifiedBy: 'admin',
    memberPackage: 'Cơ bản',
  },
  {
    id: '4',
    shopname: 'Shop Điện Tử',
    description: 'Thiết bị điện tử chính hãng',
    logoURL: '/assets/14.png',
    coverImageURL: '/assets/15.png',
    ratingAverage: 5.0,
    totalAverage: 200,
    registrationDate: new Date('2023-04-05'),
    approvalStatus: 'approved',
    approvalDate: new Date('2023-04-06'),
    bankAccountNumber: '222333444',
    bankName: 'ACB',
    taxNumber: '2223334445',
    totalProduct: 200,
    completeRate: 99,
    status: true,
    accountId: 'acc4',
    createdBy: 'admin',
    createdAt: '2023-04-05',
    lastModifiedAt: '2023-04-06',
    lastModifiedBy: 'admin',
    memberPackage: 'Kim cương',
  },
  {
    id: '5',
    shopname: 'Shop Mỹ Phẩm',
    description: 'Mỹ phẩm chính hãng nhập khẩu',
    logoURL: '/assets/15.png',
    coverImageURL: '/assets/16.png',
    ratingAverage: 4.5,
    totalAverage: 150,
    registrationDate: new Date('2023-05-12'),
    approvalStatus: 'pending',
    approvalDate: new Date('2023-05-13'),
    bankAccountNumber: '555666777',
    bankName: 'Sacombank',
    taxNumber: '5556667778',
    totalProduct: 50,
    completeRate: 92,
    status: true,
    accountId: 'acc5',
    createdBy: 'admin',
    createdAt: '2023-05-12',
    lastModifiedAt: '2023-05-13',
    lastModifiedBy: 'admin',
    memberPackage: 'Bạc',
  },
]
